-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:17:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clinic` (
  `id` INT(1) NOT NULL,
  `schedule` TIME NOT NULL,
  `assign_doc` VARCHAR(1000) NOT NULL,
  `inventory` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical` (
  `id` INT(5) NOT NULL,
  `bmi` VARCHAR(20) NOT NULL,
  `dental` VARCHAR(1000) NOT NULL,
  `diseases` VARCHAR(1000) NOT NULL,
  `clinic_id` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_medical_clinic1_idx` (`clinic_id` ASC) VISIBLE,
  CONSTRAINT `fk_medical_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `mydb`.`clinic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`school` (
  `id` INT(5) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT(8) NOT NULL,
  `lname` VARCHAR(25) NOT NULL,
  `fname` VARCHAR(25) NOT NULL,
  `mi` VARCHAR(2) NULL,
  `cor` VARCHAR(35) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `dob` DATE NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `medical_id` INT(5) NOT NULL,
  `school_id` INT(5) NOT NULL,
  `clinic_id` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_student_medical_idx` (`medical_id` ASC) VISIBLE,
  INDEX `fk_student_school1_idx` (`school_id` ASC) VISIBLE,
  INDEX `fk_student_clinic1_idx` (`clinic_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_medical`
    FOREIGN KEY (`medical_id`)
    REFERENCES `mydb`.`medical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `mydb`.`clinic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL,
  `title` VARCHAR(10) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `units` INT(2) NOT NULL,
  `department_id` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `id` VARCHAR(7) NOT NULL,
  `time` TIME NOT NULL,
  `section` VARCHAR(20) NOT NULL,
  `room` INT(3) NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_class_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_has_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_has_class` (
  `student_id` INT(8) NOT NULL,
  `student_medical_id` INT(5) NOT NULL,
  `student_school_id` INT(5) NOT NULL,
  `student_clinic_id` INT(1) NOT NULL,
  `class_id` VARCHAR(7) NOT NULL,
  INDEX `fk_student_has_class_class1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_student_has_class_student1_idx` (`student_id` ASC, `student_medical_id` ASC, `student_school_id` ASC, `student_clinic_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_class_student1`
    FOREIGN KEY (`student_id` , `student_medical_id` , `student_school_id` , `student_clinic_id`)
    REFERENCES `mydb`.`student` (`id` , `medical_id` , `school_id` , `clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` VARCHAR(5) NOT NULL,
  `fname` VARCHAR(100) NOT NULL,
  `lname` VARCHAR(100) NOT NULL,
  `mname` VARCHAR(100) NULL,
  `type` VARCHAR(11) NOT NULL,
  `student_id` INT(8) NOT NULL,
  `student_medical_id` INT(5) NOT NULL,
  `student_school_id` INT(5) NOT NULL,
  `student_clinic_id` INT(1) NOT NULL,
  `school_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_student1_idx` (`student_id` ASC, `student_medical_id` ASC, `student_school_id` ASC, `student_clinic_id` ASC) VISIBLE,
  INDEX `fk_staff_school1_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_student1`
    FOREIGN KEY (`student_id` , `student_medical_id` , `student_school_id` , `student_clinic_id`)
    REFERENCES `mydb`.`student` (`id` , `medical_id` , `school_id` , `clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `id` VARCHAR(5) NOT NULL,
  `level` INT(1) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `department_id` VARCHAR(10) NOT NULL,
  `school_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_program_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_program_school1_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
