-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:44:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `lname` VARCHAR(45) NULL,
  `fname` VARCHAR(45) NULL,
  `initial` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `ticket_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `ticket_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `ticket_id1`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_ticket_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_customer_payment1_idx` (`payment_id` ASC) VISIBLE,
  INDEX `fk_customer_ticket1_idx` (`ticket_id1` ASC) VISIBLE,
  CONSTRAINT `fk_customer_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_ticket1`
    FOREIGN KEY (`ticket_id1`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `lname` VARCHAR(45) NULL,
  `fname` VARCHAR(45) NULL,
  `initial` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attraction` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attraction_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_attraction_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attraction_has_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attraction_has_customer` (
  `attraction_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`attraction_id`, `customer_id`),
  INDEX `fk_attraction_has_customer_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_attraction_has_customer_attraction1_idx` (`attraction_id` ASC) VISIBLE,
  CONSTRAINT `fk_attraction_has_customer_attraction1`
    FOREIGN KEY (`attraction_id`)
    REFERENCES `mydb`.`attraction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attraction_has_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_has_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee_has_ticket` (
  `employee_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `ticket_id`),
  INDEX `fk_employee_has_ticket_ticket1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_employee_has_ticket_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_ticket_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_ticket_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attraction_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attraction_has_employee` (
  `attraction_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`attraction_id`, `employee_id`),
  INDEX `fk_attraction_has_employee_employee1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_attraction_has_employee_attraction1_idx` (`attraction_id` ASC) VISIBLE,
  CONSTRAINT `fk_attraction_has_employee_attraction1`
    FOREIGN KEY (`attraction_id`)
    REFERENCES `mydb`.`attraction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attraction_has_employee_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deptname` VARCHAR(45) NULL,
  `depttype` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Department_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
